# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 16:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range_start', models.DateField()),
                ('range_end', models.DateField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dest_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dest_country', to='countries.Country')),
                ('src_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='src_country', to='countries.Country')),
            ],
        ),
    ]
