# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 06:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20161022_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='profiles.Profile'),
        ),
    ]
