# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.SlugField(max_length=1000, unique=True),
        ),
    ]
