# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20161111_0413'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to='user_photos'),
            preserve_default=False,
        ),
    ]
